export default {
  "products": [
    {
      "id": 1,
      "name": "Nike Swoosh Crop T-Shirt",
      "brand": "Nike",
      "category": "shirts",
      "description": "Nike Swoosh Crop T-Shirt",
      "availableSizes": ["S", "M", "L", "XL"],
      "price": 34.90,
      "original": 49.00,
      "isFreeShipping": true,
      "image": "/images/d1.jpeg",
      "rating": 4.5,
      "numReviews": 10,
    },
    {
      "id": 2,
      "name": "Nike Boyfriend T-Shirt",
      "brand": "Nike",
      "category": "shirts",
      "description": "Nike Boyfriend T-Shirt",
      "availableSizes": ["XS", "S", "M", "L"],
      "price": 35.00,
      "original": 35.00,
      "isFreeShipping": true,
      "image": "/images/d2.jpeg",
      "rating": 4.2,
      "numReviews": 12
    },
    {
      "id": 3,
      "name": "Nike Swoosh Crop Top",
      "brand": "Nike",
      "category": "shirts",
      "description": "Nike Swoosh Crop Top",
      "availableSizes": ["XL", "M", "L"],
      "price": 49.90,
      "original": 49.90,
      "isFreeShipping": true,
      "image": "/images/d3.jpeg",
      "rating": 4.2,
      "numReviews": 13
    },
    {
      "id": 4,
      "name": "Nike Air Crop T-Shirt",
      "brand": "Nike",
      "category": "shirts",
      "description": "Nike Air Crop T-Shirt",
      "availableSizes": ["S", "M", "L", "XL"],
      "price": 34.30,
      "original": 49.00,
      "isFreeShipping": false,
      "image": "/images/d4.jpeg",
      "rating": 4.1,
      "numReviews": 13
    },
    {
      "id": 5,
      "name": "Nike Air T-Shirt",
      "brand": "Nike",
      "category": "shirts",
      "description": "Nike Air T-Shirt",
      "availableSizes": ["S", "M", "L", "XL"],
      "price": 34.30,
      "original": 49.00,
      "isFreeShipping": false,
      "image": "/images/d5.jpeg",
      "rating": 4.3,
      "numReviews": 15
    },
    {
      "id": 6,
      "name": "Nike Training Pro Tank Top",
      "brand": "Nike",
      "category": "shirts",
      "description": "Nike Training Pro Tank Top",
      "availableSizes": ["XS", "S", "M", "L", "XL"],
      "price": 35.00,
      "original": 35.00,
      "isFreeShipping": false,
      "image": "/images/d6.jpeg",
      "rating": 4.4,
      "numReviews": 21
    },
    {
      "id": 7,
      "name": "Crazy Monkey Black T-Shirt",
      "brand": "Nike",
      "category": "shirts",
      "description": "1977 Infantil",
      "availableSizes": ["M", "L", "XL", "XXL"],
      "price": 39.00,
      "original": 39.00,
      "isFreeShipping": true,
      "image": "/images/d7.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 8,
      "name": "Nike Pro Training 3 Inch Shorts In Black",
      "brand": "Nike",
      "category": "shorts",
      "description": "Nike Pro Training 3 Inch Shorts In Black",
      "availableSizes": ["M", "L", "XL", "XXL"],
      "price": 40.90,
      "original": 40.90,
      "isFreeShipping": true,
      "image": "/images/d8.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 9,
      "name": "Nike Pro Training 3 inch shorts with mesh inserts in Black",
      "brand": "Nike",
      "category": "shorts",
      "description": "Nike Pro Training 3 inch shorts with mesh inserts in Black",
      "availableSizes": ["M", "L", "XL", "XXL"],
      "price": 50.90,
      "original": 50.90,
      "isFreeShipping": true,
      "image": "/images/d9.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 10,
      "name": "Nike Training Icon Clash Pro 3 inch shorts in Black",
      "brand": "Nike",
      "category": "shorts",
      "description": "Nike Training Icon Clash Pro 3 inch shorts in Black",
      "availableSizes": ["M", "L", "XL", "XXL"],
      "price": 50.90,
      "original": 50.90,
      "isFreeShipping": true,
      "image": "/images/d10.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 12,
      "name": "Nike Training 3 inch shorts in black sparkle print",
      "brand": "Nike",
      "category": "shorts",
      "description": "Nike Training 3 inch shorts in black sparkle print",
      "availableSizes": ["M", "L", "XL", "XXL"],
      "price": 50.90,
      "original": 50.90,
      "isFreeShipping": true,
      "image": "/images/d12.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 13,
      "name": "Nike Pro Training 3 inch shorts with marble print in Black",
      "brand": "Nike",
      "category": "shorts",
      "description": "Nike Pro Training 3 inch shorts with marble print in Black",
      "availableSizes": ["M", "L", "XL", "XXL"],
      "price": 50.90,
      "original": 50.90,
      "isFreeShipping": true,
      "image": "/images/d13.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 14,
      "name": "Wolf & Whistle tie dye shorts in stone",
      "brand": "Nike",
      "category": "shorts",
      "description": "Wolf & Whistle tie dye shorts in stone",
      "availableSizes": ["M", "L", "XL"],
      "price": 16.30,
      "original": 49.90,
      "isFreeShipping": true,
      "image": "/images/d14.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 15,
      "name": "Nike Football dry academy shorts in black with side taping",
      "brand": "Nike",
      "category": "shorts",
      "description": "Nike Football dry academy shorts in black with side taping",
      "availableSizes": ["XS", "M", "L"],
      "price": 29.90,
      "original": 29.90,
      "isFreeShipping": true,
      "image": "/images/d15.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 16,
      "name": "Wolf & Whistle zebra print shorts in black",
      "brand": "Nike",
      "category": "shorts",
      "description": "Wolf & Whistle zebra print shorts in black",
      "availableSizes": ["XS", "XL", "XXL"],
      "price": 12.90,
      "original": 43.90,
      "isFreeShipping": true,
      "image": "/images/d16.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 17,
      "name": "Wolf & Whistle recycled shorts with leopard print band in teal",
      "brand": "Nike",
      "category": "shorts",
      "description": "Wolf & Whistle recycled shorts with leopard print band in teal",
      "availableSizes": ["XS", "XL", "XXL"],
      "price": 12.90,
      "original": 43.90,
      "isFreeShipping": true,
      "image": "/images/d17.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 18,
      "name": "Under Armour Training play up shorts in pink",
      "brand": "Nike",
      "category": "shorts",
      "description": "Under Armour Training play up shorts in pink",
      "availableSizes": ["M", "L", "XL"],
      "price": 42.90,
      "original": 42.90,
      "isFreeShipping": true,
      "image": "/images/d18.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 19,
      "name": "South Beach seamless booty shorts in light blue",
      "brand": "Nike",
      "category": "shorts",
      "description": "South Beach seamless booty shorts in light blue",
      "availableSizes": ["M", "L", "XL"],
      "price": 27.90,
      "original": 27.90,
      "isFreeShipping": true,
      "image": "/images/d19.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 20,
      "name": "HIIT ruched booty shorts in grey",
      "brand": "HIIT",
      "category": "shorts",
      "description": "HIIT ruched booty shorts in grey",
      "availableSizes": ["M", "L"],
      "price": 33.90,
      "original": 33.90,
      "isFreeShipping": true,
      "image": "/images/d20.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 21,
      "name": "Nike stripe runner shorts",
      "brand": "Nike",
      "category": "shorts",
      "description": "Nike stripe runner shorts",
      "availableSizes": ["S", "M", "L"],
      "price": 52.90,
      "original": 52.90,
      "isFreeShipping": true,
      "image": "/images/d21.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 22,
      "name": "ASOS 4505 icon woven short with underlayer",
      "brand": "Nike",
      "category": "shorts",
      "description": "ASOS 4505 icon woven short with underlayer",
      "availableSizes": ["XS", "S", "M", "L", "XL"],
      "price": 42.90,
      "original": 42.90,
      "isFreeShipping": true,
      "image": "/images/d22.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 24,
      "name": "HIGH-WAIST ALO BRILLIANCE BIKER SHORT",
      "brand": "Nike",
      "category": "shorts",
      "description": "HIGH-WAIST ALO BRILLIANCE BIKER SHORT",
      "availableSizes": ["XL", "XXL"],
      "price": 64.90,
      "original": 64.90,
      "isFreeShipping": true,
      "image": "/images/d24.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 25,
      "name": "Nike Training Swoosh Bra",
      "brand": "Nike",
      "category": "undergarments",
      "description": "Nike Training Swoosh Bra",
      "availableSizes": ["M", "S", "XS"],
      "price": 50.90,
      "original": 50.90,
      "isFreeShipping": true,
      "image": "/images/d25.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 26,
      "name": "Nike Training Indy Logo Bra",
      "brand": "Nike",
      "category": "undergarments",
      "description": "Nike Training Indy Logo Bra",
      "availableSizes": ["XS", "S", "M", "L", "XL"],
      "price": 60.90,
      "original": 60.90,
      "isFreeShipping": true,
      "image": "/images/d26.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 27,
      "name": "Nike Sports Bra",
      "brand": "Nike",
      "category": "undergarments",
      "description": "Nike Sports Bra",
      "availableSizes": ["M", "S", "XS"],
      "price": 48.90,
      "original": 69.90,
      "isFreeShipping": true,
      "image": "/images/d27.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 28,
      "name": "Nike Training Swoosh bra in yellow",
      "brand": "Nike",
      "category": "undergarments",
      "description": "Nike Training Swoosh bra in yellow",
      "availableSizes": ["XS", "S", "M", "L", "XL", "XXL"],
      "price": 60.90,
      "original": 60.90,
      "isFreeShipping": true,
      "image": "/images/d28.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 29,
      "name": "Nike swoosh unitard in black",
      "brand": "Nike",
      "category": "shorts",
      "description": "Nike swoosh unitard in black",
      "availableSizes": ["M", "L", "XL"],
      "price": 65.90,
      "original": 65.90,
      "isFreeShipping": true,
      "image": "/images/d29.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 30,
      "name": "Nike swoosh unitard in red",
      "brand": "Nike",
      "category": "shorts",
      "description": "Nike swoosh unitard in red",
      "availableSizes": ["M", "L", "S"],
      "price": 65.90,
      "original": 65.90,
      "isFreeShipping": true,
      "image": "/images/d30.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 31,
      "name": "Puma unitard in lilac - exclusive to ASOS",
      "brand": "Nike",
      "category": "shorts",
      "description": "Puma unitard in lilac - exclusive to ASOS",
      "availableSizes": ["XS", "S", "M", "L", "XL"],
      "price": 65.90,
      "original": 65.90,
      "isFreeShipping": true,
      "image": "/images/d31.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 32,
      "name": "Puma unitard in rose - exclusive to ASOS",
      "brand": "Nike",
      "category": "shorts",
      "description": "Puma unitard in rose - exclusive to ASOS",
      "availableSizes": ["XS", "S", "M", "L", "XL"],
      "price": 65.90,
      "original": 65.90,
      "isFreeShipping": true,
      "image": "/images/d32.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 33,
      "name": "Lasula lounge glitter unitard in gold",
      "brand": "Nike",
      "category": "shorts",
      "description": "Lasula lounge glitter unitard in gold",
      "availableSizes": ["M", "L", "S"],
      "price": 36.90,
      "original": 52.90,
      "isFreeShipping": true,
      "image": "/images/d33.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 34,
      "name": "Puma Logo Capri Unitard in red exclusive at ASOS",
      "brand": "Nike",
      "category": "shorts",
      "description": "Puma Logo Capri Unitard in red exclusive at ASOS",
      "availableSizes": ["S", "XS"],
      "price": 41.90,
      "original": 61.90,
      "isFreeShipping": true,
      "image": "/images/d34.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 35,
      "name": "Nike Training Icon Clash seamless bra in purple print",
      "brand": "Nike",
      "category": "undergarments",
      "description": "Nike Training Icon Clash seamless bra in purple print",
      "availableSizes": ["XS", "S", "M", "L", "XL", "XXL"],
      "price": 64.90,
      "original": 64.90,
      "isFreeShipping": true,
      "image": "/images/d35.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 36,
      "name": "Emerald Sports Bra",
      "brand": "Emerald",
      "category": "undergarments",
      "description": "Emerald Sports Bra",
      "availableSizes": ["S", "XS"],
      "price": 119.90,
      "original": 119.90,
      "isFreeShipping": true,
      "image": "/images/d36.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 37,
      "name": "Quicker Dry Wrap Sports Bra",
      "brand": "Nike",
      "category": "undergarments",
      "description": "Quicker Dry Wrap Sports Bra",
      "availableSizes": ["M", "L", "S", "XS"],
      "price": 119.90,
      "original": 119.90,
      "isFreeShipping": true,
      "image": "/images/d37.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 38,
      "name": "Nike Swoosh Icon Clash",
      "brand": "Nike",
      "category": "undergarments",
      "description": "Nike Swoosh Icon Clash",
      "availableSizes": ["XS", "S", "M", "L", "XL"],
      "price": 55.90,
      "original": 55.90,
      "isFreeShipping": true,
      "image": "/images/d38.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 39,
      "name": "Nike Indy",
      "brand": "Nike",
      "category": "undergarments",
      "description": "Nike Indy",
      "availableSizes": ["XS", "S", "M", "L"],
      "price": 55.90,
      "original": 55.90,
      "isFreeShipping": true,
      "image": "/images/d39.jpeg",
      "rating": 4.2,
      "numReviews": 22
    },
    {
      "id": 40,
      "name": "Nike Yoga favourites bra in black",
      "brand": "Nike",
      "category": "undergarments",
      "description": "Nike Yoga favourites bra in black",
      "availableSizes": ["XS", "S", "M", "L", "XL"],
      "price": 50.90,
      "original": 50.90,
      "isFreeShipping": true,
      "image": "/images/d40.jpeg",
      "rating": 4.2,
      "numReviews": 22
    }
  ]
}